import netscape.javascript.JSObject;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Scanner;

public class OracleApp
{
    // fetch weather data at given location
    public static JSObject getWeatherData(String locationName)
    {
        // get location coords using geolocation API
        JSONArray locationData = getLocationData(locationName);

        // extract latitude & longitude from first object (0) (city name)
        JSONObject location = (JSONObject) locationData.get(0);
        double latitude = (double) location.get("latitude");
        double longitude = (double) location.get("longitude");

        // build api request with coordinates to acess historical data
        String urlString = "https://historical-forecast-api.open-meteo.com/v1/forecast?" + "latitude=" + 52.52 +"&longitude=" + 13.41 + "&start_date=2025-04-20&end_date=2025-05-04&hourly=temperature_2m,weather_code,wind_speed_10m,relative_humidity_2m,precipitation_probability,precipitation";

        try
        {
            // call api, get response
            HttpURLConnection conn = fetchApiResponse(urlString);

            if (conn.getResponseCode() != 200)
            {
                System.out.println("Error: Could not connect to API");
                return null;
            }

            StringBuilder resultJson = new StringBuilder();
            Scanner scanner = new Scanner(conn.getInputStream());
            while (scanner.hasNext())
            {
                resultJson.append(scanner.nextLine());
            }
            // housekeeping (close scanner and url connection)
            scanner.close();
            conn.disconnect();

            // parse data
            JSONParser parser = new JSONParser();
            JSONObject resultJsonObj = (JSONObject) parser.parse(String.valueOf(resultJson));

            // retrieve hourly data
            JSONObject hourly = (JSONObject) resultJsonObj.get("hourly");
            JSONArray time = (JSONArray) hourly.get("time");

        }catch (Exception e)
        {
            e.printStackTrace();
        }
        //todo: return real stuff?
        return null;
    }

    // weather forecast api requires longitude/latitude, use this to convert:
    public static JSONArray getLocationData(String locationName)
    {
        // replace whitespace in location to "+" for API request
        locationName = locationName.replaceAll(" ", "+");

        // building API url
        String urlString = "https://geocoding-api.open-meteo.com/v1/search?name=" + locationName + "&count=10&language=en&format=json";

        try
        {
            // call api
            HttpURLConnection conn = fetchApiResponse(urlString);

            // check response status (200 = success)
            if (conn.getResponseCode() != 200)
            {
                System.out.println("Error: Could not connect to API");
                return null;
            }
            else
            {
                StringBuilder resultJson = new StringBuilder();
                Scanner scanner = new Scanner(conn.getInputStream());

                // read and store json data returned from our request
                while (scanner.hasNext())
                {
                    resultJson.append(scanner.nextLine());
                }

                // close scanner and url connection
                scanner.close();
                conn.disconnect();

                // parse json string into object
                JSONParser parser = new JSONParser();
                JSONObject resultJsonObj = (JSONObject) parser.parse(String.valueOf(resultJson));

                // get list of location data generated by API
                JSONArray locationData = (JSONArray) resultJsonObj.get("results");
                return locationData;

            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        //couldn't find location
        System.out.println("1");
        return null;
    }
    private static HttpURLConnection fetchApiResponse(String urlString)
    {
        try
        {
            URL url = new URL(urlString);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();

            // set reuest method to get
            conn.setRequestMethod("GET");

            //connect to API
            conn.connect();
            return conn;
        }catch (IOException e)
        {
            e.printStackTrace();
        }

        // connection could not be made in this case
        System.out.println("2");
        return null;
    }
}
